# Generated by Django 3.1.7 on 2021-09-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notesmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
